### PR TITLE
Feat progress checker

### PR DESCRIPTION
**Pull request by philison**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | - |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | custom differential drive robot |

---

## Description of contribution in a few bullet points

* Modified the simple_progress_checker Controller-Plugin to track the angular displacement/progress in addition to the linear movement
* Therefore a control effort is also successful if the robot is only rotating, given that the `required_movement_angle` requirement is met
* If the added `required_movement_angle` parameter is set to `0.0` or not declared, the angular displacement will be ignored and the behavior is the same as with the old simple_progress_checker (Should this option rather be implemented with a separate parameter?)

## Description of documentation updates required from your changes

* So far the following parameters were added:
      - `required_movement_angle`: sets the angular limit that the robot has to move to make progress, [radians]
* Therefore the default configs and documentation page need to be edited to represent the new parameter as well as the new capabilities

---

## Future work that may be required in bullet points

* Optional: Add a parameter that makes the angular progress checking optional, as it does not work correctly for robots that rotate very fast. With very fast robots, however, it would only lead to false negatives, meaning that the successful progress is not detected. Therefore it would equal the default simple_progress_checker behavior, which ignores rotational progress entirely. 
* It might be necessary to redesign the calculation as I am not 100% happy how it is currently "coded"/restructured. The default linear distance is always refers to the robot pose at the moment of the last reset, while the angular distance calculation sums up all minor pose changes between resets. (resets meaning that the linear or angular progress was achieved).  
- fast angular wiggeling of the robot adds up which could lead to unwanted progress success
- the same goes for nav stack with an indecisive global planner infront of an obstacle

### CODE REVIEW

**Comment by philison** [comment]
Lets leave the branch open after merging it into main so that I can use it to merge it to the ros-planning/navigation2 repo, after removing the angsa specific changes.

**Comment by karl-schulz** [comment]
Please remove the log statements

**Comment by karl-schulz** [comment]
I did it in https://github.com/angsa-robotics/navigation2/commit/656bca883f318e803477b44f93a93874b55e57b0

**Comment by philison** [comment]
Thanks !

**Pull request merged**
